### ISSUE TITLE
TODO List Tracker

### ISSUE THREAD

**Issue by ecwu** [heimoshuiyu/chatgpt-api-web#3]
- Refactor current template select design
  - [ ] replace the card design into a dropdown select design
  - [ ] place the template edit tools into setting panel
- Unify the style
  - [ ] make the coloring consistent for `primary`, `secondary`, `ancent` elements.
- Replace button with other elements
  - [ ] for image/TTS button aside chat textarea, replace it with icons, or rearrange the element to keep the interface tidy.

**Comment by ecwu** [comment]
We introduce a new UI design with shadcn/ui, this issues is outdated.
